"""Add employee_id

Revision ID: 0e58b8377485
Revises: 
Create Date: 2026-06-15 15:21:58.716978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e58b8377485'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('requester_email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
