"""Add deactivated_at and is_archived

Revision ID: f2077b400793
Revises: 0e58b8377485
Create Date: 2026-06-15 16:23:01.233585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2077b400793'
down_revision = '0e58b8377485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
